name: libsystemd-journal-upload
version: 0.1.0.0
github: "j1r1k/libsystemd-journal-upload"
license: BSD3
author: "Jiri Marsicek"
maintainer: "jiri.marsicek@gmail.com"
copyright: "2016 Jiri Marsicek"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/j1r1k/libsystemd-journal-upload#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base64
  - bytestring
  - directory >= 1.3.7.0
  - exceptions
  - extra
  - filepath
  - http-client
  - http-client-tls
  - http-types
  - iso8601-time
  - libsystemd-journal
  - mtl
  - network-uri
  - pcre2
  - pipes
  - pipes-safe
  - retry
  - simple-logger
  - text
  - time
  - unordered-containers
  - utf8-string

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  libsystemd-journal-upload-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - libsystemd-journal-upload
