name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('libsystemd-journal-upload.cabal') }}

    - name: Build
      run: stack build

    - name: Test
      run: stack test
